spring:
  docker:
    compose:
      enabled: true
      file: [ example/docker-compose.yaml ]
  kafka:
    bootstrap-servers: localhost:10000
management:
  endpoints:
    web:
      exposure:
        include: kafkaStreamsTopology
